#!/bin/bash

set -euxo pipefail

if [[ $# -lt 2 ]]; then
  echo "usage: $0 from_dir efi_dir"
  exit 1
fi

from_dir=${1}
efi_dir=${2}

install -dm0755 -p "${efi_dir}" || true

cp "${from_dir}/"* "${efi_dir}/"
